[package]
name = "rust-bot"
version = "0.1.0"
authors = ["Daniel <Daniel.Milholland@icloud.com>"]

[dependencies]
discord = { git = "https://github.com/SpaceManiac/discord-rs.git" }
hyper = "0.9.3"
serde_json = "*"
