[package]
name = "rust-bot"
version = "0.1.0"
authors = ["Daniel <Daniel.Milholland@icloud.com>"]

[dependencies]
discord = { git = "https://github.com/SpaceManiac/discord-rs.git" }
serde_json = "0.7"
rand = "0.3"
xi-unicode = "0.0"
hyper = "1.1.0"
