[package]
name = "rust-bot"
version = "0.1.0"
authors = ["Daniel <Daniel.Milholland@icloud.com>"]

[dependencies]
discord = { git = "https://github.com/SpaceManiac/discord-rs.git" }
hyper = "0.9.6"
serde_json = "0.7.1"
rand = "0.3.14"
xi-unicode = "0.0"
